title : Manuela AYO
baseurl : ""
repository : Manuela-AYO/manuelaayo.github.io

# collections
collections:
  projects:
    output : true

# define the layout of each page
defaults :
  - scope:
      path: ""
      type: "posts"
    values:
      layout: news

  - scope:
      path: ""
    values:
      layout: default
      

# author info
author : 
  name : Manuela AYO
  email : manuelaayo7@gmail.com
  github : Manuela-AYO


# exclude from processing
exclude : 
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - "*.lock"
